root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = [
    "assets", 
    "tmp", 
    "vendor", 
    "testdata", 
    "client", 
    ".git",
    "**/client",  # Explicitly ignore client folder at any depth
    "**/**/client"  # Catch nested client folders
  ]
  exclude_file = [
    "**/client/**/*",  # Exclude all files in any client folder
    "**/**/client/**/*"  # Catch nested client folder files
  ]
  exclude_regex = [
    "_test\\.go",
    "^client/.*",  # Ignore anything starting with client/
    "^.*/client/.*"  # Ignore client folder at any depth
  ]
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false